// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAFYOObw2JZS7cvTO2j-lxEa0jX29P8HI',
    appId: '1:872175793503:web:b2cac77445f451fa82b2ea',
    messagingSenderId: '872175793503',
    projectId: 'codex-8cda3',
    authDomain: 'codex-8cda3.firebaseapp.com',
    storageBucket: 'codex-8cda3.firebasestorage.app',
    measurementId: 'G-33ERXRTLG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJHT7sxy5JnnerZKyIethzEfyiwQWeqyk',
    appId: '1:872175793503:android:a26dd589b4a4609c82b2ea',
    messagingSenderId: '872175793503',
    projectId: 'codex-8cda3',
    storageBucket: 'codex-8cda3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFAikYeJWMMh82CqG0S6bN8gfFCMsCqcw',
    appId: '1:872175793503:ios:17de51159009fb4382b2ea',
    messagingSenderId: '872175793503',
    projectId: 'codex-8cda3',
    storageBucket: 'codex-8cda3.firebasestorage.app',
    iosBundleId: 'com.codex.codex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAFYOObw2JZS7cvTO2j-lxEa0jX29P8HI',
    appId: '1:872175793503:web:ed1ccf6ca4e9fffa82b2ea',
    messagingSenderId: '872175793503',
    projectId: 'codex-8cda3',
    authDomain: 'codex-8cda3.firebaseapp.com',
    storageBucket: 'codex-8cda3.firebasestorage.app',
    measurementId: 'G-LXBN7RPGP2',
  );
}
